### PR TITLE
adaptat to accept, preview and render videos

### PR DESCRIPTION
**Pull request by dmp593**
Hi @EduardoJM,

I loved your project. It perfectly suits my needs for my admin website, and I'm very grateful for your contribution.

However, I made a few small changes to match the current specifications, as my client also uploads videos and wants to see previews.

I am considering modifying the project to support chunked uploads, as videos often lead to a 413 Entity Too Large response.

For now, that’s it!

I'm sorry I didn't add any tests. I'm not familiar with the tool you used to build the project. I am accustomed to using Poetry, but this pyproject seemed to use a different tool.

So, for now, I just installed the dependencies into a local virtual environment using pip.

Could you please explain how to set up the project and run the tests?

Once again, I am very grateful for this gem of a project.

Best regards,
Daniel Pinto.

### CODE REVIEW

**Comment by dmp593** [comment]
By the way, in my last commit, I fixed a bug in your library that caused the image/video asset to render regardless of whether an image or video was present. This issue occurred when the response was a bad request due to errors in some form fields. Consequently, it created an inconsistent state where the form could not be submitted because the input files had a null value.

**Comment by EduardoJM** [comment]
Hello! Sorrry for the long wait time,

I will test and verify the changes and validate this to this project. 

Maybe, we can add support, in the future, for other files too, likely a little bit modern file uploader.

**Comment by dmp593** [comment]
Thank you so much! :D

**Comment by bigsbug** [comment]
@dmp593 I was looking for a widget to support video and image previews and found your PR. I tested it and it was amazing, thanks for your efforts

**Comment by dmp593** [comment]
> @dmp593 I was looking for a widget to support video and image previews and found your PR. I tested it and it was amazing, thanks for your efforts

Hey, I'm so glad to hear this!
Thank you a lot! <3

Happy New Year btw 🎉

**Pull request closed without merging**
